### ISSUE TITLE
The Saturation Depth Does Not Appear to Be Respected

### ISSUE THREAD

**Issue by Calebsakhtar** [MIT-LAE/APCEMM#16]
I have noticed that the saturation depth (meant to be 1000m) does not appear to be respected in the current version of APCEMM. See the figures below:

![fig-alt](https://github.com/MIT-LAE/APCEMM/assets/46966291/0aed5e37-9870-410f-9de4-1f58a1cd99b2)
![fig-RHi](https://github.com/MIT-LAE/APCEMM/assets/46966291/41292737-9383-4253-ba88-7f9a5d8955ca)
The RHi and altitude are both taken with index selection at x_i = 0 and y_i = 0 so they are not representative of the contrail centre.

The `input.yaml` file I used is available [here](https://pastebin.com/7F51qMxh)

@michaelxu3
@sdeastham

**Comment by sdeastham** [comment]
This is very strange. @michaelxu3 - any ideas?

**Comment by sdeastham** [comment]
Thanks @Calebsakhtar ! In v1.2.0 we are going to be disabling non-netCDF input, in part because of issues like this. Stay tuned...

**Comment by sdeastham** [comment]
PR #33 now provides a straightforward way to generate idealized meteorological data (thanks @Calebsakhtar ).

**Comment by Calebsakhtar** [comment]
@sdeastham Since your PR https://github.com/MIT-LAE/APCEMM/pull/43 only netcdf inputs are allowed. I believe we can close this issue now.
