### ISSUE TITLE
Vertical velocities from netCDF input

### ISSUE THREAD

**Issue by thabbott** [MIT-LAE/APCEMM#17]
I've been running some APCEMM simulations with met data read from a netCDF file and have noticed what seems like strange behavior: I get different results from a simulation that doesn't read vertical velocities and from a simulation that reads a vertical velocity field that's zero everywhere.

This zip archive includes a sample netCDF file and two YAML files that reproduce this issue:

[input.zip](https://github.com/user-attachments/files/15839317/input.zip)

When I run without reading vertical velocities (w_off.yaml), I get this IWC field after 1 hour:

<img width="548" alt="image" src="https://github.com/MIT-LAE/APCEMM/assets/11680078/c5b98e8c-90ca-4c0e-b1f6-ad4af06d90f1">

When I run a simulation that reads vertical velocities equal to zero everywhere (w_on.yaml), I get a different result:

<img width="529" alt="image" src="https://github.com/MIT-LAE/APCEMM/assets/11680078/272f8ec9-ef39-4954-a747-a8c40ae8093b">

(I'm open to the possibility that this is an issue with the way I've set up my APCEMM input files--if that's the case please let me know!)

**Comment by sdeastham** [comment]
Thanks @thabbott ! I've now had a chance to look into this in more detail, and I think that the vertical velocity code basically needs an overhaul. A re-write of vertical velocity handling is now slated for v1.2.0; you can follow this on issue https://github.com/MIT-LAE/APCEMM/issues/26. I'll close this issue for now though as the fix you develop in https://github.com/contrailcirrus/pycontrails/commit/c697345d76968c8f06e1cbd3324c9e619cdb7717 is also the recommended approach.
