### ISSUE TITLE
Default options to track contrail location too permissive resulting in very long simulations

### ISSUE THREAD

**Issue by sdeastham** [MIT-LAE/APCEMM#42]
_Issue first noted by @Calebsakhtar_ 

Since https://github.com/MIT-LAE/APCEMM/commit/e1245bc6e9fbfd74d9cd71a9d24a454a85b47bf3, regions affected by the contrail are tracked even when the ice has evaporated locally. This allows earlier evaporated crystals to affect later ones, but currently we use a very permissive approach where any location with > 1 particle per m3 is counted as "contrail", leaving a contrail tracer behind, and affected air is tracked for a very long time (until the contrail tracer has fallen to < 20% due to continued diffusion). The buffer added to the domain at each time step also assumes that crystals can fall from the lowermost boundary at maximum speed, which is unlikely to be true when the ice crystals are not themselves setting the boundary. This combination of factors results in very large simulation domains.

**Comment by Calebsakhtar** [comment]
Currently working on some analysis that will yield better understanding of the effects of changing the above mentioned model threshold.

Results should be posted early this week.

**Comment by Calebsakhtar** [comment]
@sdeastham I cannot close this issue - do you want to keep it open?

**Comment by sdeastham** [comment]
Nope! Thanks for the ping - I think we can consider this to be a closed issue now, although we will need to keep working on making the model more efficient of course.
