### ISSUE TITLE
Error with Eigen Dependency during APCEMM compilation

### ISSUE THREAD

**Issue by Calebsakhtar** [MIT-LAE/APCEMM#6]
###  Current Behavior:
Attempting to build APCEMM within a Docker image results in the following terminal error:

> Consolidate compiler generated dependencies of target FVM_ANDS
> [ 10%] Building CXX object src/FVM_ANDS/CMakeFiles/FVM_ANDS.dir/AdvDiffSystem.cpp.o
> In file included from /home/APCEMM/Code.v05-00/src/FVM_ANDS/AdvDiffSystem.cpp:1:
> /home/APCEMM/Code.v05-00/include/FVM_ANDS/AdvDiffSystem.hpp: In member function 'void FVM_ANDS::AdvDiffSystem::updatePhi(const VectorXd&)':
> /home/APCEMM/Code.v05-00/include/FVM_ANDS/AdvDiffSystem.hpp:46:29: error: 'seq' is not a member of 'Eigen'; did you mean '__pstl::execution::v1::seq'?
>    46 |                 phi_(Eigen::seq(0, nx_ * ny_ - 1)) = phi_new(Eigen::seq(0, nx_ * ny_ - 1));
>       |                             ^~~
> In file included from /usr/local/include/c++/9.3.0/pstl/glue_algorithm_defs.h:15,
>                  from /usr/local/include/c++/9.3.0/algorithm:71,
>                  from /usr/include/eigen3/Eigen/Core:288,
>                  from /usr/include/eigen3/Eigen/SparseCore:11,
>                  from /usr/include/eigen3/Eigen/Sparse:26,
>                  from /home/APCEMM/Code.v05-00/include/FVM_ANDS/AdvDiffSystem.hpp:4,
>                  from /home/APCEMM/Code.v05-00/src/FVM_ANDS/AdvDiffSystem.cpp:1:
> /usr/local/include/c++/9.3.0/pstl/execution_defs.h:112:28: note: '__pstl::execution::v1::seq' declared here
>   112 | constexpr sequenced_policy seq{};
>       |                            ^~~
> In file included from /home/APCEMM/Code.v05-00/src/FVM_ANDS/AdvDiffSystem.cpp:1:
> /home/APCEMM/Code.v05-00/include/FVM_ANDS/AdvDiffSystem.hpp:46:69: error: 'seq' is not a member of 'Eigen'; did you mean '__pstl::execution::v1::seq'?
>    46 |                 phi_(Eigen::seq(0, nx_ * ny_ - 1)) = phi_new(Eigen::seq(0, nx_ * ny_ - 1));
>       |                                                                     ^~~
> In file included from /usr/local/include/c++/9.3.0/pstl/glue_algorithm_defs.h:15,
>                  from /usr/local/include/c++/9.3.0/algorithm:71,
>                  from /usr/include/eigen3/Eigen/Core:288,
>                  from /usr/include/eigen3/Eigen/SparseCore:11,
>                  from /usr/include/eigen3/Eigen/Sparse:26,
>                  from /home/APCEMM/Code.v05-00/include/FVM_ANDS/AdvDiffSystem.hpp:4,
>                  from /home/APCEMM/Code.v05-00/src/FVM_ANDS/AdvDiffSystem.cpp:1:
> /usr/local/include/c++/9.3.0/pstl/execution_defs.h:112:28: note: '__pstl::execution::v1::seq' declared here
>   112 | constexpr sequenced_policy seq{};
>       |                            ^~~
> make[2]: *** [src/FVM_ANDS/CMakeFiles/FVM_ANDS.dir/build.make:76: src/FVM_ANDS/CMakeFiles/FVM_ANDS.dir/AdvDiffSystem.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1296: src/FVM_ANDS/CMakeFiles/FVM_ANDS.dir/all] Error 2
> make: *** [Makefile:101: all] Error 2

### Expected Behavior:
No error messages should appear when building APCEMM from the VS Docker terminal.

### Steps To Reproduce:
1. Git checkout to commit ending in `1b07fbb`
2. Open the APCEMM folder in VS Code
3. Run Docker
4. Install the "Dev Containers" VS Code extension (if not already installed)
5. Open the APCEMM folder in a VS Docker image by following the [Dev Containers tutorial here](https://code.visualstudio.com/docs/devcontainers/tutorial)
6. On the VS Docker image terminal: `cd APCEMM/Code.v05-00`
7. On the VS Docke image terminal: `cmake .`
8. On the VS Docke image terminal: `cmake --build .`

### Environment Details
VS Code version: 1.83.1
Dev Containers version: 0.315.1
Docker version: 4.24.0
OS: Windows 10 Pro
OS Version: 22H2
OS Build: 19045.3570

### Anything else:
I have tried the following steps to fix this so far without success:
- Installing Eigen from the VS Docker terminal before running the CMAKE commands by using: `sudo apt install libeigen3-dev`

This is a follow-on issue to APCEMM issue #5.

@sdeastham @michaelxu3 @ddrake-mitre

**Comment by ddrake-mitre** [comment]
@Calebsakhtar see [this PR](https://github.com/MIT-LAE/APCEMM/pull/7) for an update that I made while making sure we had the latest changes to APCEMM. This should be the fix you need.

**Comment by Calebsakhtar** [comment]
@ddrake-mitre Thank you so much! Worked like a charm.

This issue is now closed.
